package pl.lato.views.opinie;

import java.util.Arrays;
import java.util.List;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.charts.Chart;
import com.vaadin.flow.component.charts.model.Configuration;
import com.vaadin.flow.component.charts.model.Crosshair;
import com.vaadin.flow.component.charts.model.ListSeries;
import com.vaadin.flow.component.charts.model.XAxis;
import com.vaadin.flow.component.charts.model.YAxis;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.polymertemplate.Id;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.data.renderer.TemplateRenderer;
import com.vaadin.flow.router.AfterNavigationEvent;
import com.vaadin.flow.router.AfterNavigationObserver;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.templatemodel.TemplateModel;
import pl.lato.views.opinie.OpinieView.OpinieViewModel;
import pl.lato.views.main.MainView;

@Route(value = "opinie", layout = MainView.class)
@PageTitle("Opinie")
@JsModule("./src/views/opinie/opinie-view.js")
@Tag("opinie-view")
public class OpinieView extends PolymerTemplate<OpinieViewModel> implements AfterNavigationObserver {

    // This is the Java companion file of a design
    // You can find the design file in
    // /frontend/src/views/src/views/opinie/opinie-view.js
    // The design can be easily edited by using Vaadin Designer
    // (vaadin.com/designer)

    /**
     * All data we send to the client (template). Implementation is generated by the
     * framework.
     */
    public static interface OpinieViewModel extends TemplateModel {

        public void setItems(List<Person> items);
    }

    public OpinieView() {
    }

    @Override
    public void afterNavigation(AfterNavigationEvent event) {

        // Set some data when this view is displayed.
        List<Person> persons = Arrays.asList( //
                createPerson("", "Sebastian Lato", "May 8",
                        "Wszystko ok",
                        "12", "0", "2")


        );

        getModel().setItems(persons);
    }

    private static Person createPerson(String image, String name, String date, String post, String likes,
            String comments, String shares) {
        Person p = new Person();
        p.setImage(image);
        p.setName(name);
        p.setDate(date);
        p.setPost(post);
        p.setLikes(likes);
        p.setComments(comments);
        p.setShares(shares);

        return p;
    }

}
